services:
    dmzx.usernamecolourchanger.listener:
        class: dmzx\usernamecolourchanger\event\listener
        arguments:
            - @request
            - @template
            - @user
            - @auth
            - @dbal.conn
        tags:
            - { name: event.listener }
